- hosts: localhost
  tasks: 
    - name: Install zsh
      include_tasks: tasks/install-zsh.yaml
      tags:
      - dev-tools
      - terminal

    - name: Install asdf
      include_tasks: tasks/install-asdf.yaml
      tags:
      - dev-tools

    - name: Install Node and NPM
      include_tasks: tasks/install-node-via-asdf.yaml
      tags:
      - dev-tools